## **1. Rationale**
###
A meta-analysis plays a key role in evidence synthesis and is preceded by a systematic review of the literature. After formulation of the research question (cf. PICO) and specification of criteria for eligibility, a systematic literature search is conducted using prespecified search strategies for bibliographic databases. Search results are screened for eligibility and relevant studies are selected for subsequent synthesis. Before the evidence synthesis, relevant information such as the effect estimate is extracted from all included studies. Furthermore, the risk of bias should be assessed in each individual study. Finally, effect estimates from conceptually similar studies are combined using meta-analytic techniques. Results from evidence synthesis should be reported in accordance with the PRISMA Statement (Moher et al., 2009).

###
#### **Bibliographic Databases/Search Engines**
[CINAHL](https://ebscohost.com/nursing/products/cinahl-databases/the-cinahl-database)  
[Cochrane Library](https://cochranelibrary.com)  
[Embase](https://elsevier.com/solutions/embase-biomedical-research)  
[Google Scholar](https://scholar.google.com)  
[MEDLINE](https://ncbi.nlm.nih.gov/pubmed)  
[Web of Science](https://webofknowledge.com)  

### **References**
Bailar JC III (1997) The promise and problems of meta-analysis. *N Engl J Med* 337:559-561  

Feinstein AR (1995) Meta-analysis: Statistical alchemy for the 21st century. *J Clin Epidemiol* 48:71-79  

Ioannidis JPA (2009) Integration of evidence from multiple meta-analyses: A primer on umbrella reviews, treatment networks and multiple treatments meta-analyses. *CMAJ* 181:488-493  

Ioannidis JPA, Patsopoulos NA, Rothstein HR (2008) Reasons or excuses for avoiding meta-analysis in forest plots. *BMJ* 336:1413-1415  
  
Macleod MR, Michie S, Roberts I, Dirnagl U, Chalmers I, Ioannidis JPA, Al-Shahi Salman R, Chan A-W, Glasziou P (2014) Biomedical research: Increasing value, reducing waste. *Lancet* 383:101-104  

Moher D, Liberati A, Tetzlaff J, Altman DG, The PRISMA Group (2009) Preferred reporting items for systematic reviews and meta-analyses: The PRISMA Statement. *PLoS Med* 6: e1000097  

Shapiro S (1997) Is meta-analysis a valid approach to the evaluation of small effects in observational studies? *J Clin Epidemiol* 50:223-229  

Thompson SG, Pocock SJ (1991) Can meta-analyses be trusted? *Lancet* 338:1127-1130
